### ISSUE TITLE
Missing 1.5.6?

### ISSUE THREAD

**Issue by michaelbeil** [peiche/cover#37]
The changelog is at 1.5.6, but you updated packages and such to 1.5.6.1. Perhaps you skipped a beat locally?

https://github.com/peiche/cover/pull/36/files#diff-0a08a7565aba4405282251491979bb6bL3
https://github.com/peiche/cover/pull/36/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L3
![screen shot 2015-07-22 at 12 31 04 pm](https://cloud.githubusercontent.com/assets/4752949/8832269/9c4ff332-306d-11e5-975e-0d937c47cc39.png)

**Comment by peiche** [comment]
Yeah, with even more changes pending. I'll be finishing up 1.6 soon enough, then everything will be back to normal.

**Comment by peiche** [comment]
Updated to [1.6](https://github.com/peiche/cover/pull/38).
