### ISSUE TITLE
Customizer conflict

### ISSUE THREAD

**Issue by michaelbeil** [peiche/cover#43]
Upon working with Cover in the customizer, I received an error notice and was not able to do any further customizations. After some time in FTP, Git, and MySQL, it seems like the error is coming from Cover. Very strange.

**Comment by peiche** [comment]
What was the error? Can you reproduce it?

**Comment by michaelbeil** [comment]
`GET http://staging1.michaelbeil.com/wp-content/themes/cover/js/customizer.js?ver=20130508 404 (Not Found load-scripts.php?c=0&load[]=underscore,customize-base,wp-a11y,customize-controls,jquery-ui-core,jqu…:9`

**Comment by michaelbeil** [comment]
http://beil.io/apLw

**Comment by peiche** [comment]
Huh. What version of Cover?

**Comment by michaelbeil** [comment]
1.6.2

**Comment by michaelbeil** [comment]
I found the culprit.

**Comment by michaelbeil** [comment]
SG CacehPress

**Comment by peiche** [comment]
The problem is here: https://github.com/peiche/cover/blob/master/inc/customizer.php#L257

The line should be '/dist/js/customizer.js'. Fix incoming.

**Comment by michaelbeil** [comment]
Oh say oh say. Yup, now there is that, too.

**Comment by michaelbeil** [comment]
Had not quite gone to that line yet.

**Comment by michaelbeil** [comment]
Quality work here my man.
