### ISSUE TITLE
Galleries broken

### ISSUE THREAD

**Issue by allytibbitt** [peiche/cover#57]
Hi,

Recent upgrades of Cover and/or Aesop Story Engine seem to have broken something. None of the Aesop components are displaying full width. Example [here ](https://theferret.scot/calais-requiem-dream-photo-essay/)

Really love this theme, and we depend on it, so get in touch if you need any help.

**Comment by peiche** [comment]
Remove the selector `.entry-content > div` from line 41 of your child theme's CSS. That should fix it.

**Comment by allytibbitt** [comment]
Cheers :)
