### ISSUE TITLE
Featured image margin

### ISSUE THREAD

**Issue by allytibbitt** [peiche/cover#70]
Since updating theme to latest version, there's an issue with the featured image. On desktop, whitespace has appeared on the left margin, which I can't see how to get rid of using CSS. 

Here's a screen grab. It makes no difference whether I use "old" cover-featured.php code which retains the excerpt display or the latest version of cover-featured.php

https://goo.gl/photos/JXDHxhDFxfDZcYkc9

All help much appreciated.

**Comment by allytibbitt** [comment]
Fixed this myself by adding: 

```
.featured-container ul, ol {
    margin: 0 0 0 0;
}
```

**Comment by peiche** [comment]
Addressed in #71
