### ISSUE TITLE
Featured image now overlays over posts

### ISSUE THREAD

**Issue by allytibbitt** [peiche/cover#72]
After last update, the featured image now sits over the front page and hides the top stories. It should push content beneath it. Affects all devices. 

Screen grab: https://goo.gl/photos/hsND4Geiat3F8DKn9

**Comment by peiche** [comment]
Are you on v1.7.7? If you are, I suspect it's a cached stylesheet. My suggestion would be to clear your cache and refresh the page.

If that fixes it, then I'll just have to make sure I include a cache-buster in the next release's stylesheet. If not, I have a couple other ideas.

**Comment by allytibbitt** [comment]
Yep, on v1.7.7. I've cleared the cache and that didn't help :( I've cloned our site, with the broken featured image showing, so you can have a look at a live site with this problem: http://wordpress-18307-40229-120490.cloudwaysapps.com/

As ever, grateful for your help.
