### ISSUE TITLE
Post Listing Style

### ISSUE THREAD

**Issue by cogdog** [peiche/cover#75]
In customizer -> Cover View Options, under columns it reads:

> Applied when Cover View Options -> Post Listing Style is set to Grid.

But my only Listing styles are **Minimal** and **Card**- I am guessing **Card** = **Grid** ? Just trying to make sure I have not missed a style.

**Comment by peiche** [comment]
That would be a typo. Yes, card = grid. I'll fix all the typos on the next release.
