### ISSUE TITLE
Default Gravatar Broken Icon in Header

### ISSUE THREAD

**Issue by cogdog** [peiche/cover#76]
I'm not sure the default images for user w/o gravatar is broken URL; see as an example:

https://certificates.creativecommons.org/2016/04/help-us-build/

where the code for the author image is:

`get_avatar( get_the_author_meta( 'ID' ), 35, 'avatar_default', 'Profile Picture for ' . esc_html( get_the_author() ) )`

results in bad image URL for avatar http://i0.wp.com/avatar_default

whereas the code for the author in the bio 

` get_avatar( get_the_author_meta( 'ID' ), ( is_author() ? 120 : 80 ) ); `

works fine.

**Comment by cogdog** [comment]
Thanks, you are quick!

**Comment by peiche** [comment]
My pleasure.
