### ISSUE TITLE
Captioned image with alignnone class aligned with screen left instead of content left

### ISSUE THREAD

**Issue by uusijani** [peiche/cover#82]
### Steps to reproduce

Add an image to a post, type in a caption and set alignment to 'None'.

### What I expect to happen

I'd expect the captioned image to be left-aligned with the main content column's left, in line with `<p>` elements.

### What happens

The image is left-aligned to the left edge of the screen. [My attachment](https://user-images.githubusercontent.com/4244772/29924125-8858b240-8e64-11e7-8c1f-9a731ff50e7e.png) is a screenshot of a post with one uncaptioned and one captioned alignnone image.

**Comment by peiche** [comment]
Captioned, left- or right-aligned images are expected to do this. The same behavior exists for Aesop Story Engine images, as well. Closing.
